import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    // Navigation & Header
    settings: "Settings",
    profile: "Profile",
    home: "Home",

    // Auth
    signInWithGoogle: "Continue with Google",
    signInWithEmail: "Sign in with Email",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    enterCredentials: "Enter your credentials to access your dashboard",
    joinCelluiq: "Join Celluiq to optimize your health",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    signIn: "Sign In",
    signUp: "Sign Up",
    sendResetLink: "Send Reset Link",
    dontHaveAccount: "Don't have an account? ",
    alreadyHaveAccount: "Already have an account? ",
    checkYourEmail: "Check Your Email",
    resetLinkSent: "We have sent a password reset link to",
    returnToLogin: "Return to Login",
    terms: "Terms",
    policy: "Policy",
    byContinuing: "By continuing, you agree to our",
    resetPassword: "Reset Password",
    enterEmailReset: "Enter your email to receive a reset link",

    // Home Page
    yourCelluiqScore: "YOUR CELLUIQ SCORE",
    outstandingProgress: "Outstanding progress this week. Your biomarkers are trending toward optimal ranges.",
    markers: "Markers",
    stack: "Stack",
    nutrition: "Nutrition",
    routine: "Routine",

    // Blood Markers
    bloodMarkers: "Blood Markers",
    latestResults: "Latest Results",
    uploadResults: "Upload Results",
    optimal: "Optimal",
    suboptimal: "Suboptimal",
    needAttention: "Need Attention",
    optimalRange: "Optimal range",
    recommendedMarkers: "Recommended Markers",
    missingMarkers: "Missing Markers",
    downloadMarkerList: "Download Marker List",
    markersToTest: "Markers to Test",

    // Nutrition Section
    weeklyTarget: "Weekly Target",
    protein: "PROTEIN",
    carbs: "CARBS",
    fats: "FATS",
    fiber: "FIBER",
    basedOnBiomarkers: "Based on latest biomarkers",
    showAffordable: "Show affordable alternatives",
    estimatedCost: "Estimated",
    weeklyAmount: "Weekly Amount",
    dailyRecommendation: "Daily Recommendation",
    addToShoppingList: "Add to Shopping List",
    generateShoppingList: "Generate Shopping List",
    personalizedForYou: "Personalized for you",
    markersNeedAttention: "markers need attention",

    // Supplement Stack
    supplementStack: "Supplement Stack",
    daySupply: "30-Day Supply",
    personalizedBlend: "Personalized Blend",
    dailyIntake: "Daily Intake",
    whatsIncluded: "What's included",
    recommendedAddons: "Recommended Add-ons",
    basedOnBloodwork: "Based on your bloodwork",
    noRecommendationsYet: "No recommendations yet",
    uploadBloodworkSupplements: "Upload your bloodwork to get personalized supplement recommendations.",
    morningStack: "Morning Stack",
    eveningStack: "Evening Stack",
    takeWithBreakfast: "Take with breakfast",
    takeBeforeBed: "Take before bed",
    noSupplementsAdded: "No supplements added yet",
    orderPersonalizedBundle: "Order personalized bundle",
    amPmStackComingSoon: "AM/PM Stack Coming Soon",
    supplementPackages: "30-day supplement packages, personalized and delivered",
    checkDosage: "Check dosage",
    unlockWithPro: "Unlock with Pro",

    // Routine Section
    yourDailyRoutine: "Your Daily Routine",
    routineDescription: "Personalized habits to optimize your biomarkers",
    morningRoutine: "Morning Routine",
    eveningRoutine: "Evening Routine",
    exerciseRoutine: "Exercise",
    completed: "completed",
    coldShower: "Cold Shower",
    coldShowerDesc: "2-3 minutes cold water to boost cortisol and immune system",
    morningSunlight: "Morning Sunlight",
    morningSunlightDesc: "Get natural light exposure within 30 min of waking",
    breathingExercise: "Breathing Exercise",
    breathingExerciseDesc: "Box breathing or Wim Hof method for stress reduction",
    noScreens: "No Screens",
    noScreensDesc: "Avoid blue light 1 hour before sleep for better melatonin",
    meditation: "Meditation",
    meditationDesc: "Mindfulness practice to reduce cortisol and stress",
    dailyWalk: "Daily Walk",
    dailyWalkDesc: "Low-intensity movement for cardiovascular health",
    strengthTraining: "Strength Training",
    strengthTrainingDesc: "Resistance training to boost testosterone and metabolism",
    hiitTraining: "HIIT Training",
    hiitTrainingDesc: "High-intensity intervals for HGH and metabolic boost",
    magnesiumRoutine: "Magnesium Routine",
    magnesiumRoutineDesc: "Take magnesium 30 min before sleep for better rest",
    intermittentFasting: "Intermittent Fasting",
    intermittentFastingDesc: "16:8 fasting window for autophagy and energy",
    optimize: "Optimize",
    reduce: "Reduce",
    daily: "Daily",
    personalizedRoutine: "Personalized for You",
    personalizedRoutineDesc: "This routine is based on your profile, goals, and blood markers.",

    // Settings
    manageAccount: "Manage your account and preferences",
    subscription: "Subscription",
    manageSubscription: "Manage Subscription",
    manageSubscriptionDesc: "Manage your supplement subscription plan",
    connectedDevices: "Connected Devices",
    syncFitnessData: "Sync your fitness data for personalized recommendations",
    preferences: "Preferences",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    enabled: "Enabled",
    disabled: "Disabled",
    currentlyEnabled: "Currently enabled",
    notifications: "Notifications",
    getHealthReminders: "Get health reminders",
    privacySecurity: "Privacy & Security",
    manageYourData: "Manage your data",
    logout: "Logout",
    editProfile: "Edit Profile",
    aboutYou: "About You",
    gender: "Gender",
    male: "Male",
    female: "Female",
    ageGroup: "Age Group",
    activityLevel: "Activity Level",
    diet: "Diet",
    cancel: "Cancel",

    // Profile
    healthJourney: "Your health journey overview",
    bloodTests: "Blood Tests",
    healthScore: "Health Score",
    daysActive: "Days Active",
    achievements: "Achievements",
    totalImprovement: "Total Improvement",
    daysTracked: "Days Tracked",
    recentActivity: "Recent Activity",
    recentBloodTests: "Recent Blood Tests",
    about: "About",
    age: "Age",
    height: "Height",
    weight: "Weight",
    goal: "Goal",

    // Dashboard
    healthDashboard: "Health Dashboard",
    trackWellness: "Track your wellness journey in one place",
    overview: "Overview",
    vitalSigns: "Vital Signs",
    medications: "Medications",

    // Common
    backToHome: "Back to Home",
    backToSettings: "Back to Settings",
    viewProfile: "View Profile",
    save: "Save",
    select: "Select",

    // Notifications
    bloodTestReminder: "Blood Test Reminder",
    bloodTestReminderDesc: "Reminder every 3 months for new test",
    supplementReminder: "Supplement Reminder",
    supplementReminderDesc: "Daily intake reminder",
    weeklyReport: "Weekly Report",
    weeklyReportDesc: "Summary of your progress",
    newRecommendations: "New Recommendations",
    newRecommendationsDesc: "Notification for new tips",
    shoppingReminder: "Shopping Reminder",
    shoppingReminderDesc: "Weekly shopping list",
    quietHours: "Quiet Hours",
    quietHoursDesc: "No notifications during this time",
    from: "From",
    to: "To",
    manageNotifications: "Manage your notifications",

    // Pro Modal
    upgradeToPro: "Upgrade to Pro",
    unlockAllFeatures: "Unlock all premium features",
    perMonth: "/month",
    startProTrial: "Start Pro Trial",
    cancelAnytime: "Cancel anytime. 7-day free trial.",
    proFeature1: "Evening supplement recommendations",
    proFeature2: "Personalized nutrition plan",
    proFeature3: "Health device integrations",
    proFeature4: "Priority support",
    proFeature5: "Advanced biomarker insights",

    // Modals
    recommendedDosage: "Recommended Dosage",
    determineDosage: "Determine individually",
    recommendedForm: "Recommended form",
    mechanism: "Mechanism",
    intakeTime: "Intake Time",
    warnings: "Warnings",
    whyThisSupplement: "Why this supplement?",
    studiesAndSources: "Studies & Sources",
    medicalDisclaimer: "This recommendation does not replace medical advice. Always discuss supplementation with your doctor.",
    healthBenefits: "Health Benefits",
    influencedBiomarkers: "Influenced Biomarkers",
    dailyAmount: "Daily Amount",
    bestTime: "Best Time",
    optimalCombinations: "Optimal Combinations",
    yourStatus: "Your Status",
    celluiqOptimal: "CELLUIQ Optimal",
    clinicalRange: "Clinical Range",
    possibleSymptoms: "Possible Symptoms",
    supplementRecommendation: "Supplement Recommendation",
    nutritionRecommendation: "Nutrition Recommendation",
    lifestyleChanges: "Lifestyle Changes",
    asOf: "As of",

    // Categories
    proteinCategory: "Protein",
    vegetables: "Vegetables",
    fruits: "Fruits",
    grains: "Grains",
    dairy: "Dairy",
    healthyFats: "Healthy Fats",
    nutsSeeds: "Nuts & Seeds",
    legumes: "Legumes",
    seafood: "Seafood",
    herbsSpices: "Herbs & Spices",
    beverages: "Beverages",
    other: "Other",

    // Upload
    welcomeToCelluiq: "Welcome to CELLUIQ",
    uploadFirstBloodwork: "Upload your first bloodwork and get personalized health recommendations",
    uploadBloodwork: "Upload Bloodwork",
    pdfPngJpg: "PDF, PNG or JPG",
    orderBloodTest: "Order Blood Test",
    completePanel: "Complete panel from",
    addManually: "Add manually",

    // Onboarding
    genderQuestion: "What is your biological sex?",
    genderSubtitle: "For sex-specific reference ranges",
    ageQuestion: "How old are you?",
    ageSubtitle: "For age-appropriate recommendations",
    years: "Years",
    biometricsQuestion: "Body Measurements",
    biometricsSubtitle: "For your BMI and nutrition plan",
    cm: "cm",
    kg: "kg",
    bloodworkQuestion: "Upload your bloodwork",
    bloodworkSubtitle: "PDF or image of your lab results",
    selectFile: "Select File",
    uploading: "Uploading...",
    saving: "Saving...",
    skipUpload: "I don't have bloodwork (Skip)",
    manualEntryLater: "You can enter values manually later.",
    encryptedData: "Your data is encrypted and secure.",
    validValueError: "Please enter a valid value for",
    step: "Step",
    of: "of",
    next: "Next",
    back: "Back",
    male: "Male",
    female: "Female",
  },
  de: {
    // Navigation & Header
    settings: "Einstellungen",
    profile: "Profil",
    home: "Startseite",

    // Auth
    signInWithGoogle: "Weiter mit Google",
    signInWithEmail: "Mit E-Mail anmelden",
    welcomeBack: "Willkommen zurück",
    createAccount: "Konto erstellen",
    enterCredentials: "Gib deine Anmeldedaten ein, um auf dein Dashboard zuzugreifen",
    joinCelluiq: "Werde Teil von Celluiq und optimiere deine Gesundheit",
    emailAddress: "E-Mail-Adresse",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    signIn: "Anmelden",
    signUp: "Registrieren",
    sendResetLink: "Link senden",
    dontHaveAccount: "Noch kein Konto? ",
    alreadyHaveAccount: "Bereits ein Konto? ",
    checkYourEmail: "Prüfe deine E-Mails",
    resetLinkSent: "Wir haben einen Link zum Zurücksetzen gesendet an",
    returnToLogin: "Zurück zur Anmeldung",
    terms: "AGB",
    policy: "Datenschutz",
    byContinuing: "Mit der Fortsetzung akzeptierst du unsere",
    resetPassword: "Passwort zurücksetzen",
    enterEmailReset: "Gib deine E-Mail ein, um einen Link zum Zurücksetzen zu erhalten",

    // Home Page
    yourCelluiqScore: "DEIN CELLUIQ SCORE",
    outstandingProgress: "Hervorragender Fortschritt diese Woche. Deine Biomarker tendieren zu optimalen Bereichen.",
    markers: "Marker",
    stack: "Stack",
    nutrition: "Ernährung",
    routine: "Routine",

    // Blood Markers
    bloodMarkers: "Blutwerte",
    latestResults: "Neueste Ergebnisse",
    uploadResults: "Ergebnisse hochladen",
    optimal: "Optimal",
    suboptimal: "Suboptimal",
    needAttention: "Achtung",
    optimalRange: "Optimaler Bereich",
    recommendedMarkers: "Empfohlene Marker",
    missingMarkers: "Fehlende Marker",
    downloadMarkerList: "Markerliste herunterladen",
    markersToTest: "Zu testende Marker",

    // Nutrition Section
    weeklyTarget: "Wochenziel",
    protein: "PROTEIN",
    carbs: "KOHLENHYDRATE",
    fats: "FETTE",
    fiber: "BALLASTSTOFFE",
    basedOnBiomarkers: "Basierend auf deinen Biomarkern",
    showAffordable: "Günstige Alternativen anzeigen",
    estimatedCost: "Geschätzt",
    weeklyAmount: "Wochenmenge",
    dailyRecommendation: "Tägliche Empfehlung",
    addToShoppingList: "Zur Einkaufsliste hinzufügen",
    generateShoppingList: "Einkaufsliste generieren",
    personalizedForYou: "Personalisiert für dich",
    markersNeedAttention: "Marker brauchen Aufmerksamkeit",

    // Supplement Stack
    supplementStack: "Supplement Stack",
    daySupply: "30-Tage-Vorrat",
    personalizedBlend: "Personalisierte Mischung",
    dailyIntake: "Tägliche Einnahme",
    whatsIncluded: "Was enthalten ist",
    recommendedAddons: "Empfohlene Ergänzungen",
    basedOnBloodwork: "Basierend auf deinem Blutbild",
    noRecommendationsYet: "Noch keine Empfehlungen",
    uploadBloodworkSupplements: "Lade dein Blutbild hoch, um personalisierte Supplement-Empfehlungen zu erhalten.",
    morningStack: "Morning Stack",
    eveningStack: "Evening Stack",
    takeWithBreakfast: "Mit Frühstück einnehmen",
    takeBeforeBed: "Vor dem Schlafengehen",
    noSupplementsAdded: "Noch keine Supplements hinzugefügt",
    orderPersonalizedBundle: "Personalisiertes Bundle bestellen",
    amPmStackComingSoon: "AM/PM Stack Coming Soon",
    supplementPackages: "30-Tage Supplement-Pakete, personalisiert und geliefert",
    checkDosage: "Dosierung prüfen",
    unlockWithPro: "Mit Pro freischalten",

    // Routine Section
    yourDailyRoutine: "Deine Tägliche Routine",
    routineDescription: "Personalisierte Gewohnheiten zur Optimierung deiner Biomarker",
    morningRoutine: "Morgen-Routine",
    eveningRoutine: "Abend-Routine",
    exerciseRoutine: "Bewegung",
    completed: "erledigt",
    coldShower: "Kalte Dusche",
    coldShowerDesc: "2-3 Minuten kaltes Wasser für Cortisol und Immunsystem",
    morningSunlight: "Morgenlicht",
    morningSunlightDesc: "Natürliches Licht innerhalb von 30 Min nach dem Aufwachen",
    breathingExercise: "Atemübung",
    breathingExerciseDesc: "Box-Atmung oder Wim Hof Methode zur Stressreduktion",
    noScreens: "Keine Bildschirme",
    noScreensDesc: "Blaues Licht 1 Stunde vor dem Schlaf vermeiden",
    meditation: "Meditation",
    meditationDesc: "Achtsamkeitspraxis zur Reduktion von Cortisol und Stress",
    dailyWalk: "Täglicher Spaziergang",
    dailyWalkDesc: "Bewegung niedriger Intensität für Herzgesundheit",
    strengthTraining: "Krafttraining",
    strengthTrainingDesc: "Widerstandstraining für Testosteron und Stoffwechsel",
    hiitTraining: "HIIT Training",
    hiitTrainingDesc: "Hochintensive Intervalle für HGH und Metabolismus",
    magnesiumRoutine: "Magnesium-Routine",
    magnesiumRoutineDesc: "Magnesium 30 Min vor dem Schlaf für bessere Erholung",
    intermittentFasting: "Intervallfasten",
    intermittentFastingDesc: "16:8 Fastenfenster für Autophagie und Energie",
    optimize: "optimieren",
    reduce: "reduzieren",
    daily: "Täglich",
    personalizedRoutine: "Personalisiert für dich",
    personalizedRoutineDesc: "Diese Routine basiert auf deinem Profil, Zielen und Blutwerten.",

    // Settings
    manageAccount: "Verwalte dein Konto und deine Einstellungen",
    subscription: "Abonnement",
    manageSubscription: "Abonnement verwalten",
    manageSubscriptionDesc: "Verwalte dein Supplement-Abonnement",
    connectedDevices: "Verbundene Geräte",
    syncFitnessData: "Synchronisiere Fitness-Daten für personalisierte Empfehlungen",
    preferences: "Einstellungen",
    language: "Sprache",
    darkMode: "Dunkler Modus",
    lightMode: "Heller Modus",
    enabled: "Aktiviert",
    disabled: "Deaktiviert",
    currentlyEnabled: "Derzeit aktiviert",
    notifications: "Benachrichtigungen",
    getHealthReminders: "Gesundheitserinnerungen erhalten",
    privacySecurity: "Datenschutz & Sicherheit",
    manageYourData: "Verwalte deine Daten",
    logout: "Abmelden",
    editProfile: "Profil bearbeiten",
    aboutYou: "Über dich",
    gender: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    ageGroup: "Altersgruppe",
    activityLevel: "Aktivitätslevel",
    diet: "Ernährung",
    cancel: "Abbrechen",

    // Profile
    healthJourney: "Dein Gesundheitsweg im Überblick",
    bloodTests: "Bluttests",
    healthScore: "Gesundheitsscore",
    daysActive: "Aktive Tage",
    achievements: "Erfolge",
    totalImprovement: "Gesamtverbesserung",
    daysTracked: "Verfolgte Tage",
    recentActivity: "Letzte Aktivität",
    recentBloodTests: "Letzte Bluttests",
    about: "Über dich",
    age: "Alter",
    height: "Größe",
    weight: "Gewicht",
    goal: "Ziel",

    // Dashboard
    healthDashboard: "Gesundheits-Dashboard",
    trackWellness: "Verfolge deine Wellness-Reise an einem Ort",
    overview: "Übersicht",
    vitalSigns: "Vitalzeichen",
    medications: "Medikamente",

    // Common
    backToHome: "Zurück zur Startseite",
    backToSettings: "Zurück zu Einstellungen",
    viewProfile: "Profil anzeigen",
    save: "Speichern",
    select: "Auswählen",

    // Notifications
    bloodTestReminder: "Bluttest-Erinnerung",
    bloodTestReminderDesc: "Erinnerung alle 3 Monate für neuen Test",
    supplementReminder: "Supplement-Erinnerung",
    supplementReminderDesc: "Tägliche Einnahme-Erinnerung",
    weeklyReport: "Wöchentlicher Bericht",
    weeklyReportDesc: "Zusammenfassung deiner Fortschritte",
    newRecommendations: "Neue Empfehlungen",
    newRecommendationsDesc: "Benachrichtigung bei neuen Tipps",
    shoppingReminder: "Einkaufs-Erinnerung",
    shoppingReminderDesc: "Wöchentliche Einkaufsliste",
    quietHours: "Ruhezeiten",
    quietHoursDesc: "Keine Benachrichtigungen während dieser Zeit",
    from: "Von",
    to: "Bis",
    manageNotifications: "Verwalte deine Benachrichtigungen",

    // Pro Modal
    upgradeToPro: "Upgrade auf Pro",
    unlockAllFeatures: "Alle Premium-Features freischalten",
    perMonth: "/Monat",
    startProTrial: "Pro-Testversion starten",
    cancelAnytime: "Jederzeit kündbar. 7 Tage kostenlos testen.",
    proFeature1: "Abend-Supplement-Empfehlungen",
    proFeature2: "Personalisierter Ernährungsplan",
    proFeature3: "Gesundheitsgeräte-Integration",
    proFeature4: "Prioritäts-Support",
    proFeature5: "Erweiterte Biomarker-Einblicke",

    // Modals
    recommendedDosage: "Empfohlene Dosierung",
    determineDosage: "Individuell bestimmen",
    recommendedForm: "Empfohlene Form",
    mechanism: "Wirkungsweise",
    intakeTime: "Einnahmezeitpunkt",
    warnings: "Hinweise",
    whyThisSupplement: "Warum dieses Supplement?",
    studiesAndSources: "Studien & Quellen",
    medicalDisclaimer: "Diese Empfehlung ersetzt keine ärztliche Beratung. Besprich Supplementierung immer mit deinem Arzt.",
    healthBenefits: "Gesundheitsvorteile",
    influencedBiomarkers: "Beeinflusste Biomarker",
    dailyAmount: "Tägliche Menge",
    weeklyAmountLabel: "Wöchentliche Menge",
    bestTime: "Beste Einnahmezeit",
    optimalCombinations: "Optimale Kombinationen",
    yourStatus: "Dein Status",
    celluiqOptimal: "CELLUIQ Optimal",
    clinicalRange: "Klinischer Bereich",
    possibleSymptoms: "Mögliche Symptome",
    supplementRecommendation: "Supplement Empfehlung",
    nutritionRecommendation: "Ernährungsempfehlung",
    lifestyleChanges: "Lifestyle Änderungen",
    asOf: "Stand",

    // Categories
    proteinCategory: "Protein",
    vegetables: "Gemüse",
    fruits: "Obst",
    grains: "Getreide",
    dairy: "Milchprodukte",
    healthyFats: "Gesunde Fette",
    nutsSeeds: "Nüsse & Samen",
    legumes: "Hülsenfrüchte",
    seafood: "Meeresfrüchte",
    herbsSpices: "Kräuter & Gewürze",
    beverages: "Getränke",
    other: "Sonstige",

    // Upload
    welcomeToCelluiq: "Willkommen bei CELLUIQ",
    uploadFirstBloodwork: "Lade dein erstes Blutbild hoch und erhalte personalisierte Gesundheitsempfehlungen",
    uploadBloodwork: "Blutbild hochladen",
    pdfPngJpg: "PDF, PNG oder JPG",
    orderBloodTest: "Bluttest bestellen",
    completePanel: "Komplettes Panel ab",
    addManually: "Manuell hinzufügen",

    // Onboarding
    genderQuestion: "Was ist dein biologisches Geschlecht?",
    genderSubtitle: "Für geschlechtsspezifische Referenzwerte",
    ageQuestion: "Wie alt bist du?",
    ageSubtitle: "Für altersgerechte Empfehlungen",
    years: "Jahre",
    biometricsQuestion: "Körpermaße",
    biometricsSubtitle: "Für deinen BMI und Ernährungsplan",
    cm: "cm",
    kg: "kg",
    bloodworkQuestion: "Lade dein Blutbild hoch",
    bloodworkSubtitle: "PDF oder Bild deiner Laborergebnisse",
    selectFile: "Datei auswählen",
    uploading: "Wird hochgeladen...",
    saving: "Speichere...",
    skipUpload: "Ich habe kein Blutbild (Überspringen)",
    manualEntryLater: "Du kannst später manuell Werte eintragen.",
    encryptedData: "Deine Daten werden sicher verschlüsselt übertragen.",
    validValueError: "Bitte gib einen gültigen Wert ein für",
    step: "Schritt",
    of: "von",
    next: "Weiter",
    back: "Zurück",
    male: "Männlich",
    female: "Weiblich",
  },
  es: {
    // Navigation & Header
    settings: "Configuración",
    profile: "Perfil",
    home: "Inicio",

    // Auth
    signInWithGoogle: "Continuar con Google",
    signInWithEmail: "Iniciar sesión con Email",
    welcomeBack: "Bienvenido de nuevo",
    createAccount: "Crear Cuenta",
    enterCredentials: "Introduce tus credenciales para acceder a tu panel",
    joinCelluiq: "Únete a Celluiq para optimizar tu salud",
    emailAddress: "Dirección de Correo",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    sendResetLink: "Enviar enlace de recuperación",
    dontHaveAccount: "¿No tienes una cuenta? ",
    alreadyHaveAccount: "¿Ya tienes una cuenta? ",
    checkYourEmail: "Revisa tu correo",
    resetLinkSent: "Hemos enviado un enlace de recuperación a",
    returnToLogin: "Volver al inicio de sesión",
    terms: "Términos",
    policy: "Política",
    byContinuing: "Al continuar, aceptas nuestros",
    resetPassword: "Restablecer contraseña",
    enterEmailReset: "Introduce tu correo para recibir un enlace de restablecimiento",

    // Home Page
    yourCelluiqScore: "TU PUNTUACIÓN CELLUIQ",
    outstandingProgress: "Progreso excepcional esta semana. Tus biomarcadores tienden a rangos óptimos.",
    markers: "Marcadores",
    stack: "Stack",
    nutrition: "Nutrición",
    routine: "Rutina",

    // Blood Markers
    bloodMarkers: "Marcadores Sanguíneos",
    latestResults: "Últimos Resultados",
    uploadResults: "Subir Resultados",
    optimal: "Óptimo",
    suboptimal: "Subóptimo",
    needAttention: "Necesita Atención",
    optimalRange: "Rango óptimo",
    recommendedMarkers: "Marcadores Recomendados",
    missingMarkers: "Marcadores Faltantes",
    downloadMarkerList: "Descargar Lista de Marcadores",
    markersToTest: "Marcadores a Analizar",

    // Nutrition Section
    weeklyTarget: "Objetivo Semanal",
    protein: "PROTEÍNA",
    carbs: "CARBOHIDRATOS",
    fats: "GRASAS",
    fiber: "FIBRA",
    basedOnBiomarkers: "Basado en últimos biomarcadores",
    showAffordable: "Mostrar alternativas asequibles",
    estimatedCost: "Estimado",
    weeklyAmount: "Cantidad Semanal",
    dailyRecommendation: "Recomendación Diaria",
    addToShoppingList: "Añadir a la Lista de Compras",

    // Supplement Stack
    supplementStack: "Stack de Suplementos",
    daySupply: "Suministro de 30 Días",
    personalizedBlend: "Mezcla Personalizada",
    dailyIntake: "Ingesta Diaria",
    whatsIncluded: "Qué incluye",
    recommendedAddons: "Complementos Recomendados",

    // Routine Section
    yourDailyRoutine: "Tu Rutina Diaria",
    routineDescription: "Hábitos personalizados para optimizar tus biomarcadores",
    morningRoutine: "Rutina Matutina",
    eveningRoutine: "Rutina Nocturna",
    exerciseRoutine: "Ejercicio",
    completed: "completado",
    coldShower: "Ducha Fría",
    coldShowerDesc: "2-3 minutos de agua fría para cortisol y sistema inmune",
    morningSunlight: "Luz Matutina",
    morningSunlightDesc: "Exposición a luz natural dentro de 30 min al despertar",
    breathingExercise: "Ejercicio de Respiración",
    breathingExerciseDesc: "Respiración cuadrada o método Wim Hof para reducir estrés",
    noScreens: "Sin Pantallas",
    noScreensDesc: "Evitar luz azul 1 hora antes de dormir para mejor melatonina",
    meditation: "Meditación",
    meditationDesc: "Práctica de mindfulness para reducir cortisol y estrés",
    dailyWalk: "Caminata Diaria",
    dailyWalkDesc: "Movimiento de baja intensidad para salud cardiovascular",
    strengthTraining: "Entrenamiento de Fuerza",
    strengthTrainingDesc: "Entrenamiento de resistencia para testosterona y metabolismo",
    hiitTraining: "Entrenamiento HIIT",
    hiitTrainingDesc: "Intervalos de alta intensidad para HGH y metabolismo",
    magnesiumRoutine: "Rutina de Magnesio",
    magnesiumRoutineDesc: "Tomar magnesio 30 min antes de dormir para mejor descanso",
    intermittentFasting: "Ayuno Intermitente",
    intermittentFastingDesc: "Ventana de ayuno 16:8 para autofagia y energía",
    optimize: "optimizar",
    reduce: "reducir",
    daily: "Diario",
    personalizedRoutine: "Personalizado para Ti",
    personalizedRoutineDesc: "Esta rutina está basada en tu perfil, objetivos y marcadores.",

    // Settings
    manageAccount: "Gestiona tu cuenta y preferencias",
    subscription: "Suscripción",
    manageSubscription: "Gestionar Suscripción",
    manageSubscriptionDesc: "Gestiona tu plan de suscripción de suplementos",
    connectedDevices: "Dispositivos Conectados",
    syncFitnessData: "Sincroniza tus datos de fitness para recomendaciones personalizadas",
    preferences: "Preferencias",
    language: "Idioma",
    darkMode: "Modo Oscuro",
    currentlyEnabled: "Actualmente habilitado",
    notifications: "Notificaciones",
    getHealthReminders: "Recibir recordatorios de salud",
    privacySecurity: "Privacidad y Seguridad",
    manageYourData: "Gestiona tus datos",
    logout: "Cerrar Sesión",

    // Profile
    healthJourney: "Tu viaje de salud en resumen",
    bloodTests: "Análisis de Sangre",
    healthScore: "Puntuación de Salud",
    daysActive: "Días Activos",
    achievements: "Logros",
    totalImprovement: "Mejora Total",
    daysTracked: "Días Registrados",
    recentActivity: "Actividad Reciente",
    about: "Acerca de",
    age: "Edad",
    height: "Altura",
    weight: "Peso",
    goal: "Objetivo",

    // Dashboard
    healthDashboard: "Panel de Salud",
    trackWellness: "Rastrea tu viaje de bienestar en un solo lugar",
    overview: "Resumen",
    vitalSigns: "Signos Vitales",
    medications: "Medicamentos",

    // Common
    backToHome: "Volver al Inicio",
    backToSettings: "Volver a Configuración",
    viewProfile: "Ver Perfil",
    save: "Guardar",

    // Notifications
    bloodTestReminder: "Recordatorio de Análisis",
    bloodTestReminderDesc: "Recordatorio cada 3 meses para nuevo análisis",
    supplementReminder: "Recordatorio de Suplementos",
    supplementReminderDesc: "Recordatorio diario de ingesta",
    weeklyReport: "Informe Semanal",
    weeklyReportDesc: "Resumen de tu progreso",
    newRecommendations: "Nuevas Recomendaciones",
    newRecommendationsDesc: "Notificación de nuevos consejos",
    shoppingReminder: "Recordatorio de Compras",
    shoppingReminderDesc: "Lista de compras semanal",
    quietHours: "Horas de Silencio",
    quietHoursDesc: "Sin notificaciones durante este tiempo",
    from: "Desde",
    to: "Hasta",
    manageNotifications: "Gestiona tus notificaciones",

    // Onboarding
    genderQuestion: "¿Cuál es tu sexo biológico?",
    genderSubtitle: "Para rangos de referencia específicos",
    ageQuestion: "¿Cuántos años tienes?",
    ageSubtitle: "Para recomendaciones apropiadas a tu edad",
    years: "Años",
    biometricsQuestion: "Medidas Corporales",
    biometricsSubtitle: "Para tu IMC y plan nutricional",
    cm: "cm",
    kg: "kg",
    bloodworkQuestion: "Sube tus análisis",
    bloodworkSubtitle: "PDF o imagen de tus resultados",
    selectFile: "Seleccionar Archivo",
    uploading: "Subiendo...",
    saving: "Guardando...",
    skipUpload: "No tengo análisis (Omitir)",
    manualEntryLater: "Puedes introducir valores manualmente después.",
    encryptedData: "Tus datos están encriptados y seguros.",
    validValueError: "Por favor introduce un valor válido para",
    step: "Paso",
    of: "de",
    next: "Siguiente",
    back: "Atrás",
    male: "Masculino",
    female: "Femenino",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageInternal] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageInternal(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    // Force re-render of all components using translations
    window.dispatchEvent(new Event('languageChange'));
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};