import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation & Header
    settings: "Settings",
    profile: "Profile",
    home: "Home",
    
    // Home Page
    yourCelluiqScore: "YOUR CELLUIQ SCORE",
    outstandingProgress: "Outstanding progress this week. Your biomarkers are trending toward optimal ranges.",
    markers: "Markers",
    stack: "Stack",
    nutrition: "Nutrition",
    routine: "Routine",
    uploadFirstBlood: "Upload your first blood test to get started",
    
    // Blood Markers
    bloodMarkers: "Blood Markers",
    latestResults: "Latest Results",
    uploadResults: "Upload Results",
    optimal: "Optimal",
    suboptimal: "Suboptimal",
    needAttention: "Need Attention",
    optimalRange: "Optimal range",
    recommendedMarkers: "Recommended Markers",
    missingMarkers: "Missing Markers",
    downloadMarkerList: "Download Marker List",
    markersToTest: "Markers to Test",
    addManually: "Add manually",
    showAll: "Show all",
    noMarkersFound: "No markers found",
    
    // Nutrition Section
    weeklyTarget: "Weekly Target",
    protein: "PROTEIN",
    carbs: "CARBS",
    fats: "FATS",
    fiber: "FIBER",
    basedOnBiomarkers: "Based on latest biomarkers",
    showAffordable: "Show affordable alternatives",
    estimatedCost: "Estimated",
    weeklyAmount: "Weekly Amount",
    dailyRecommendation: "Daily Recommendation",
    addToShoppingList: "Add to Shopping List",
    generateShoppingList: "Generate Shopping List",
    personalizedForYou: "Personalized for you",
    markersNeedAttention: "markers need attention",
    noRecommendationsYet: "No recommendations yet",
    uploadBloodForNutrition: "Upload your blood test to receive personalized nutrition recommendations.",
    nutritionRecommendations: "Nutrition Recommendations",
    databaseBeingBuilt: "Based on your suboptimal markers, we can give you personalized nutrition recommendations. The database is currently being built.",
    
    // Food Categories
    proteinCat: "Protein",
    vegetablesCat: "Vegetables",
    fruitsCat: "Fruits",
    grainsCat: "Grains",
    dairyCat: "Dairy",
    fatsCat: "Healthy Fats",
    nutsSeeds: "Nuts & Seeds",
    legumesCat: "Legumes",
    seafoodCat: "Seafood",
    herbsSpices: "Herbs & Spices",
    beveragesCat: "Beverages",
    otherCat: "Other",
    
    // Supplement Stack
    supplementStack: "Supplement Stack",
    daySupply: "30-Day Supply",
    personalizedBlend: "Personalized Blend",
    dailyIntake: "Daily Intake",
    whatsIncluded: "What's included",
    recommendedAddons: "Recommended Add-ons",
    basedOnBloodwork: "Based on your blood work",
    markersNeedingAttention: "markers need attention",
    checkDosage: "Check dosage",
    orderPersonalizedBundle: "Order Personalized Bundle",
    comingSoon: "AM/PM Stack Coming Soon",
    comingSoonDesc: "30-day supplement packs, personalized and delivered",
    morningStack: "Morning Stack",
    takeWithBreakfast: "Take with breakfast",
    eveningStack: "Evening Stack",
    takeBeforeBed: "Take before bed",
    noSupplementsYet: "No supplements added yet",
    noRecommendationsYetSupp: "No recommendations yet",
    uploadBloodForSupplements: "Upload your blood test to receive personalized supplement recommendations.",
    
    // Routine Section
    yourDailyRoutine: "Your Daily Routine",
    routineDescription: "Personalized habits to optimize your biomarkers",
    morningRoutine: "Morning Routine",
    eveningRoutine: "Evening Routine",
    exerciseRoutine: "Exercise",
    completed: "completed",
    coldShower: "Cold Shower",
    coldShowerDesc: "2-3 minutes cold water to boost cortisol and immune system",
    morningSunlight: "Morning Sunlight",
    morningSunlightDesc: "Get natural light exposure within 30 min of waking",
    breathingExercise: "Breathing Exercise",
    breathingExerciseDesc: "Box breathing or Wim Hof method for stress reduction",
    noScreens: "No Screens",
    noScreensDesc: "Avoid blue light 1 hour before sleep for better melatonin",
    meditation: "Meditation",
    meditationDesc: "Mindfulness practice to reduce cortisol and stress",
    dailyWalk: "Daily Walk",
    dailyWalkDesc: "Low-intensity movement for cardiovascular health",
    strengthTraining: "Strength Training",
    strengthTrainingDesc: "Resistance training to boost testosterone and metabolism",
    hiitTraining: "HIIT Training",
    hiitTrainingDesc: "High-intensity intervals for HGH and metabolic boost",
    magnesiumRoutine: "Magnesium Routine",
    magnesiumRoutineDesc: "Take magnesium 30 min before sleep for better rest",
    intermittentFasting: "Intermittent Fasting",
    intermittentFastingDesc: "16:8 fasting window for autophagy and energy",
    optimize: "Optimize",
    reduce: "Reduce",
    daily: "Daily",
    personalizedRoutine: "Personalized for You",
    personalizedRoutineDesc: "This routine is based on your profile, goals, and blood markers.",
    
    // Settings
    manageAccount: "Manage your account and preferences",
    subscription: "Subscription",
    manageSubscription: "Manage Subscription",
    manageSubscriptionDesc: "Manage your supplement subscription plan",
    connectedDevices: "Connected Devices",
    syncFitnessData: "Sync your fitness data for personalized recommendations",
    preferences: "Preferences",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    currentlyEnabled: "Currently enabled",
    notifications: "Notifications",
    getHealthReminders: "Get health reminders",
    privacySecurity: "Privacy & Security",
    manageYourData: "Manage your data",
    logout: "Logout",
    editProfile: "Edit Profile",
    aboutYou: "About You",
    gender: "Gender",
    male: "Male",
    female: "Female",
    ageRange: "Age Range",
    activityLevel: "Activity Level",
    diet: "Diet",
    unlockWithPro: "Unlock with Pro",
    upgradeToPro: "Upgrade to Pro",
    allFeaturesFor: "All features for",
    perMonth: "/month",
    lastBloodTests: "Recent Blood Tests",
    tests: "Tests",
    score: "Score",
    
    // Profile
    healthJourney: "Your health journey overview",
    bloodTests: "Blood Tests",
    healthScore: "Health Score",
    daysActive: "Days Active",
    achievements: "Achievements",
    totalImprovement: "Total Improvement",
    daysTracked: "Days Tracked",
    recentActivity: "Recent Activity",
    about: "About",
    age: "Age",
    height: "Height",
    weight: "Weight",
    goal: "Goal",
    
    // Dashboard
    healthDashboard: "Health Dashboard",
    trackWellness: "Track your wellness journey in one place",
    overview: "Overview",
    vitalSigns: "Vital Signs",
    medications: "Medications",
    
    // Common
    backToHome: "Back to Home",
    backToSettings: "Back to Settings",
    viewProfile: "View Profile",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving...",
    select: "Select",
    enabled: "Enabled",
    disabled: "Disabled",
    
    // Notifications
    bloodTestReminder: "Blood Test Reminder",
    bloodTestReminderDesc: "Reminder every 3 months for new test",
    supplementReminder: "Supplement Reminder",
    supplementReminderDesc: "Daily intake reminder",
    weeklyReport: "Weekly Report",
    weeklyReportDesc: "Summary of your progress",
    newRecommendations: "New Recommendations",
    newRecommendationsDesc: "Notification for new tips",
    shoppingReminder: "Shopping Reminder",
    shoppingReminderDesc: "Weekly shopping list",
    quietHours: "Quiet Hours",
    quietHoursDesc: "No notifications during this time",
    from: "From",
    to: "To",
    manageNotifications: "Manage your notifications",
    
    // Pro Modal
    upgradeToProTitle: "Upgrade to Pro",
    unlockFeatures: "Unlock all premium features and take control of your health",
    startProTrial: "Start Pro Trial",
    cancelAnytime: "Cancel anytime. 7-day free trial.",
    proFeature1: "Evening supplement recommendations",
    proFeature2: "Personalized nutrition plan",
    proFeature3: "Health device integrations",
    proFeature4: "Priority support",
    proFeature5: "Advanced biomarker insights",
    
    // Blood Marker Detail
    yourStatus: "Your Status",
    celluiqOptimal: "CELLUIQ Optimal",
    clinicalRange: "Clinical Range",
    possibleSymptoms: "Possible Symptoms",
    supplementRecommendation: "Supplement Recommendation",
    form: "Form",
    nutritionRecommendation: "Nutrition Recommendation",
    lifestyleChanges: "Lifestyle Changes",
    warnings: "Warnings",
    studiesAndSources: "Studies & Sources",
    medicalDisclaimer: "This information does not replace medical advice. Always discuss changes with your doctor.",
    
    // Supplement Modal
    recommendedDosage: "Recommended Dosage",
    determineIndividually: "Determine individually",
    recommendedForm: "Recommended form",
    howItWorks: "How it Works",
    intakeTime: "Intake Time",
    eveningBeforeSleep: "Evening before sleep",
    morningWithFattyMeal: "Morning with fatty meal",
    onEmptyOrWithVitC: "On empty stomach or with Vitamin C",
    withFattyMeal: "With fatty meal",
    withAMeal: "Take with a meal",
    notes: "Notes",
    whyThisSupplement: "Why this supplement?",
    basedOnYourLevel: "Based on your",
    levelValue: "level, this supplement can help optimize your values.",
    low: "low",
    elevated: "elevated",
    
    // Food Modal
    healthBenefits: "Health Benefits",
    influencedBiomarkers: "Influenced Biomarkers",
    dailyAmount: "Daily Amount",
    weeklyAmountModal: "Weekly Amount",
    bestIntakeTime: "Best Intake Time",
    optimalCombinations: "Optimal Combinations",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    anytime: "Anytime",
    withMeal: "With a meal",
    beforeWorkout: "Before workout",
    afterWorkout: "After workout",
  },
  de: {
    // Navigation & Header
    settings: "Einstellungen",
    profile: "Profil",
    home: "Startseite",
    
    // Home Page
    yourCelluiqScore: "DEIN CELLUIQ SCORE",
    outstandingProgress: "Hervorragender Fortschritt diese Woche. Deine Biomarker tendieren zu optimalen Bereichen.",
    markers: "Marker",
    stack: "Stack",
    nutrition: "Ernährung",
    routine: "Routine",
    uploadFirstBlood: "Lade dein erstes Blutbild hoch um zu starten",
    
    // Blood Markers
    bloodMarkers: "Blutwerte",
    latestResults: "Neueste Ergebnisse",
    uploadResults: "Ergebnisse hochladen",
    optimal: "Optimal",
    suboptimal: "Suboptimal",
    needAttention: "Aufmerksamkeit erforderlich",
    optimalRange: "Optimaler Bereich",
    recommendedMarkers: "Empfohlene Marker",
    missingMarkers: "Fehlende Marker",
    downloadMarkerList: "Markerliste herunterladen",
    markersToTest: "Zu testende Marker",
    addManually: "Manuell hinzufügen",
    showAll: "Alle anzeigen",
    noMarkersFound: "Keine Marker gefunden",
    
    // Nutrition Section
    weeklyTarget: "Wochenziel",
    protein: "PROTEIN",
    carbs: "KOHLENHYDRATE",
    fats: "FETTE",
    fiber: "BALLASTSTOFFE",
    basedOnBiomarkers: "Basierend auf neuesten Biomarkern",
    showAffordable: "Günstige Alternativen anzeigen",
    estimatedCost: "Geschätzt",
    weeklyAmount: "Wochenmenge",
    dailyRecommendation: "Tägliche Empfehlung",
    addToShoppingList: "Zur Einkaufsliste hinzufügen",
    generateShoppingList: "Einkaufsliste generieren",
    personalizedForYou: "Personalisiert für dich",
    markersNeedAttention: "Marker brauchen Aufmerksamkeit",
    noRecommendationsYet: "Noch keine Empfehlungen",
    uploadBloodForNutrition: "Lade dein Blutbild hoch, um personalisierte Ernährungsempfehlungen zu erhalten.",
    nutritionRecommendations: "Ernährungsempfehlungen",
    databaseBeingBuilt: "Basierend auf deinen suboptimalen Markern können wir dir personalisierte Ernährungsempfehlungen geben. Die Datenbank wird gerade aufgebaut.",
    
    // Food Categories
    proteinCat: "Protein",
    vegetablesCat: "Gemüse",
    fruitsCat: "Obst",
    grainsCat: "Getreide",
    dairyCat: "Milchprodukte",
    fatsCat: "Gesunde Fette",
    nutsSeeds: "Nüsse & Samen",
    legumesCat: "Hülsenfrüchte",
    seafoodCat: "Meeresfrüchte",
    herbsSpices: "Kräuter & Gewürze",
    beveragesCat: "Getränke",
    otherCat: "Sonstige",
    
    // Supplement Stack
    supplementStack: "Supplement Stack",
    daySupply: "30-Tage-Vorrat",
    personalizedBlend: "Personalisierte Mischung",
    dailyIntake: "Tägliche Einnahme",
    whatsIncluded: "Was enthalten ist",
    recommendedAddons: "Empfohlene Ergänzungen",
    basedOnBloodwork: "Basierend auf deinem Blutbild",
    markersNeedingAttention: "Marker benötigen Aufmerksamkeit",
    checkDosage: "Dosierung prüfen",
    orderPersonalizedBundle: "Personalisiertes Bundle bestellen",
    comingSoon: "AM/PM Stack Coming Soon",
    comingSoonDesc: "30-Tage Supplement-Pakete, personalisiert und geliefert",
    morningStack: "Morning Stack",
    takeWithBreakfast: "Mit Frühstück einnehmen",
    eveningStack: "Evening Stack",
    takeBeforeBed: "Vor dem Schlafengehen",
    noSupplementsYet: "Noch keine Supplements hinzugefügt",
    noRecommendationsYetSupp: "Noch keine Empfehlungen",
    uploadBloodForSupplements: "Lade dein Blutbild hoch, um personalisierte Supplement-Empfehlungen zu erhalten.",
    
    // Routine Section
    yourDailyRoutine: "Deine Tägliche Routine",
    routineDescription: "Personalisierte Gewohnheiten zur Optimierung deiner Biomarker",
    morningRoutine: "Morgen-Routine",
    eveningRoutine: "Abend-Routine",
    exerciseRoutine: "Bewegung",
    completed: "erledigt",
    coldShower: "Kalte Dusche",
    coldShowerDesc: "2-3 Minuten kaltes Wasser für Cortisol und Immunsystem",
    morningSunlight: "Morgenlicht",
    morningSunlightDesc: "Natürliches Licht innerhalb von 30 Min nach dem Aufwachen",
    breathingExercise: "Atemübung",
    breathingExerciseDesc: "Box-Atmung oder Wim Hof Methode zur Stressreduktion",
    noScreens: "Keine Bildschirme",
    noScreensDesc: "Blaues Licht 1 Stunde vor dem Schlaf vermeiden",
    meditation: "Meditation",
    meditationDesc: "Achtsamkeitspraxis zur Reduktion von Cortisol und Stress",
    dailyWalk: "Täglicher Spaziergang",
    dailyWalkDesc: "Bewegung niedriger Intensität für Herzgesundheit",
    strengthTraining: "Krafttraining",
    strengthTrainingDesc: "Widerstandstraining für Testosteron und Stoffwechsel",
    hiitTraining: "HIIT Training",
    hiitTrainingDesc: "Hochintensive Intervalle für HGH und Metabolismus",
    magnesiumRoutine: "Magnesium-Routine",
    magnesiumRoutineDesc: "Magnesium 30 Min vor dem Schlaf für bessere Erholung",
    intermittentFasting: "Intervallfasten",
    intermittentFastingDesc: "16:8 Fastenfenster für Autophagie und Energie",
    optimize: "optimieren",
    reduce: "reduzieren",
    daily: "Täglich",
    personalizedRoutine: "Personalisiert für dich",
    personalizedRoutineDesc: "Diese Routine basiert auf deinem Profil, Zielen und Blutwerten.",
    
    // Settings
    manageAccount: "Verwalte dein Konto und deine Einstellungen",
    subscription: "Abonnement",
    manageSubscription: "Abonnement verwalten",
    manageSubscriptionDesc: "Verwalte dein Supplement-Abonnement",
    connectedDevices: "Verbundene Geräte",
    syncFitnessData: "Synchronisiere Fitness-Daten für personalisierte Empfehlungen",
    preferences: "Einstellungen",
    language: "Sprache",
    darkMode: "Dunkler Modus",
    lightMode: "Heller Modus",
    currentlyEnabled: "Derzeit aktiviert",
    notifications: "Benachrichtigungen",
    getHealthReminders: "Gesundheitserinnerungen erhalten",
    privacySecurity: "Datenschutz & Sicherheit",
    manageYourData: "Verwalte deine Daten",
    logout: "Abmelden",
    editProfile: "Profil bearbeiten",
    aboutYou: "Über dich",
    gender: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    ageRange: "Altersgruppe",
    activityLevel: "Aktivitätslevel",
    diet: "Ernährung",
    unlockWithPro: "Mit Pro freischalten",
    upgradeToPro: "Upgrade auf Pro",
    allFeaturesFor: "Alle Features für",
    perMonth: "/Monat",
    lastBloodTests: "Letzte Bluttests",
    tests: "Tests",
    score: "Score",
    
    // Profile
    healthJourney: "Dein Gesundheitsweg im Überblick",
    bloodTests: "Bluttests",
    healthScore: "Gesundheitsscore",
    daysActive: "Aktive Tage",
    achievements: "Erfolge",
    totalImprovement: "Gesamtverbesserung",
    daysTracked: "Verfolgte Tage",
    recentActivity: "Letzte Aktivität",
    about: "Über dich",
    age: "Alter",
    height: "Größe",
    weight: "Gewicht",
    goal: "Ziel",
    
    // Dashboard
    healthDashboard: "Gesundheits-Dashboard",
    trackWellness: "Verfolge deine Wellness-Reise an einem Ort",
    overview: "Übersicht",
    vitalSigns: "Vitalzeichen",
    medications: "Medikamente",
    
    // Common
    backToHome: "Zurück zur Startseite",
    backToSettings: "Zurück zu Einstellungen",
    viewProfile: "Profil anzeigen",
    save: "Speichern",
    cancel: "Abbrechen",
    saving: "Speichern...",
    select: "Auswählen",
    enabled: "Aktiviert",
    disabled: "Deaktiviert",
    
    // Notifications
    bloodTestReminder: "Bluttest-Erinnerung",
    bloodTestReminderDesc: "Erinnerung alle 3 Monate für neuen Test",
    supplementReminder: "Supplement-Erinnerung",
    supplementReminderDesc: "Tägliche Einnahme-Erinnerung",
    weeklyReport: "Wöchentlicher Bericht",
    weeklyReportDesc: "Zusammenfassung deiner Fortschritte",
    newRecommendations: "Neue Empfehlungen",
    newRecommendationsDesc: "Benachrichtigung bei neuen Tipps",
    shoppingReminder: "Einkaufs-Erinnerung",
    shoppingReminderDesc: "Wöchentliche Einkaufsliste",
    quietHours: "Ruhezeiten",
    quietHoursDesc: "Keine Benachrichtigungen während dieser Zeit",
    from: "Von",
    to: "Bis",
    manageNotifications: "Verwalte deine Benachrichtigungen",
    
    // Pro Modal
    upgradeToProTitle: "Upgrade auf Pro",
    unlockFeatures: "Schalte alle Premium-Features frei und nimm deine Gesundheit in die Hand",
    startProTrial: "Pro Testversion starten",
    cancelAnytime: "Jederzeit kündbar. 7 Tage kostenlos.",
    proFeature1: "Abend-Supplement Empfehlungen",
    proFeature2: "Personalisierter Ernährungsplan",
    proFeature3: "Gesundheitsgeräte-Integration",
    proFeature4: "Prioritäts-Support",
    proFeature5: "Erweiterte Biomarker-Insights",
    
    // Blood Marker Detail
    yourStatus: "Dein Status",
    celluiqOptimal: "CELLUIQ Optimal",
    clinicalRange: "Klinischer Bereich",
    possibleSymptoms: "Mögliche Symptome",
    supplementRecommendation: "Supplement Empfehlung",
    form: "Form",
    nutritionRecommendation: "Ernährungsempfehlung",
    lifestyleChanges: "Lifestyle Änderungen",
    warnings: "Warnhinweise",
    studiesAndSources: "Studien & Quellen",
    medicalDisclaimer: "Diese Informationen ersetzen keine ärztliche Beratung. Besprich Änderungen immer mit deinem Arzt.",
    
    // Supplement Modal
    recommendedDosage: "Empfohlene Dosierung",
    determineIndividually: "Individuell bestimmen",
    recommendedForm: "Empfohlene Form",
    howItWorks: "Wirkungsweise",
    intakeTime: "Einnahmezeitpunkt",
    eveningBeforeSleep: "Abends vor dem Schlafengehen",
    morningWithFattyMeal: "Morgens mit fetthaltiger Mahlzeit",
    onEmptyOrWithVitC: "Nüchtern oder mit Vitamin C",
    withFattyMeal: "Mit fetthaltiger Mahlzeit",
    withAMeal: "Mit einer Mahlzeit einnehmen",
    notes: "Hinweise",
    whyThisSupplement: "Warum dieses Supplement?",
    basedOnYourLevel: "Basierend auf deinem",
    levelValue: "Wert kann dieses Supplement helfen, deine Werte zu optimieren.",
    low: "niedrigen",
    elevated: "erhöhten",
    
    // Food Modal
    healthBenefits: "Gesundheitsvorteile",
    influencedBiomarkers: "Beeinflusste Biomarker",
    dailyAmount: "Tägliche Menge",
    weeklyAmountModal: "Wöchentliche Menge",
    bestIntakeTime: "Beste Einnahmezeit",
    optimalCombinations: "Optimale Kombinationen",
    morning: "Morgens",
    afternoon: "Nachmittags",
    evening: "Abends",
    anytime: "Jederzeit",
    withMeal: "Mit einer Mahlzeit",
    beforeWorkout: "Vor dem Training",
    afterWorkout: "Nach dem Training",
  },
  es: {
    // Navigation & Header
    settings: "Configuración",
    profile: "Perfil",
    home: "Inicio",
    
    // Home Page
    yourCelluiqScore: "TU PUNTUACIÓN CELLUIQ",
    outstandingProgress: "Progreso excepcional esta semana. Tus biomarcadores tienden a rangos óptimos.",
    markers: "Marcadores",
    stack: "Stack",
    nutrition: "Nutrición",
    routine: "Rutina",
    
    // Blood Markers
    bloodMarkers: "Marcadores Sanguíneos",
    latestResults: "Últimos Resultados",
    uploadResults: "Subir Resultados",
    optimal: "Óptimo",
    suboptimal: "Subóptimo",
    needAttention: "Necesita Atención",
    optimalRange: "Rango óptimo",
    recommendedMarkers: "Marcadores Recomendados",
    missingMarkers: "Marcadores Faltantes",
    downloadMarkerList: "Descargar Lista de Marcadores",
    markersToTest: "Marcadores a Analizar",
    
    // Nutrition Section
    weeklyTarget: "Objetivo Semanal",
    protein: "PROTEÍNA",
    carbs: "CARBOHIDRATOS",
    fats: "GRASAS",
    fiber: "FIBRA",
    basedOnBiomarkers: "Basado en últimos biomarcadores",
    showAffordable: "Mostrar alternativas asequibles",
    estimatedCost: "Estimado",
    weeklyAmount: "Cantidad Semanal",
    dailyRecommendation: "Recomendación Diaria",
    addToShoppingList: "Añadir a la Lista de Compras",
    
    // Supplement Stack
    supplementStack: "Stack de Suplementos",
    daySupply: "Suministro de 30 Días",
    personalizedBlend: "Mezcla Personalizada",
    dailyIntake: "Ingesta Diaria",
    whatsIncluded: "Qué incluye",
    recommendedAddons: "Complementos Recomendados",
    
    // Routine Section
    yourDailyRoutine: "Tu Rutina Diaria",
    routineDescription: "Hábitos personalizados para optimizar tus biomarcadores",
    morningRoutine: "Rutina Matutina",
    eveningRoutine: "Rutina Nocturna",
    exerciseRoutine: "Ejercicio",
    completed: "completado",
    coldShower: "Ducha Fría",
    coldShowerDesc: "2-3 minutos de agua fría para cortisol y sistema inmune",
    morningSunlight: "Luz Matutina",
    morningSunlightDesc: "Exposición a luz natural dentro de 30 min al despertar",
    breathingExercise: "Ejercicio de Respiración",
    breathingExerciseDesc: "Respiración cuadrada o método Wim Hof para reducir estrés",
    noScreens: "Sin Pantallas",
    noScreensDesc: "Evitar luz azul 1 hora antes de dormir para mejor melatonina",
    meditation: "Meditación",
    meditationDesc: "Práctica de mindfulness para reducir cortisol y estrés",
    dailyWalk: "Caminata Diaria",
    dailyWalkDesc: "Movimiento de baja intensidad para salud cardiovascular",
    strengthTraining: "Entrenamiento de Fuerza",
    strengthTrainingDesc: "Entrenamiento de resistencia para testosterona y metabolismo",
    hiitTraining: "Entrenamiento HIIT",
    hiitTrainingDesc: "Intervalos de alta intensidad para HGH y metabolismo",
    magnesiumRoutine: "Rutina de Magnesio",
    magnesiumRoutineDesc: "Tomar magnesio 30 min antes de dormir para mejor descanso",
    intermittentFasting: "Ayuno Intermitente",
    intermittentFastingDesc: "Ventana de ayuno 16:8 para autofagia y energía",
    optimize: "optimizar",
    reduce: "reducir",
    daily: "Diario",
    personalizedRoutine: "Personalizado para Ti",
    personalizedRoutineDesc: "Esta rutina está basada en tu perfil, objetivos y marcadores.",
    
    // Settings
    manageAccount: "Gestiona tu cuenta y preferencias",
    subscription: "Suscripción",
    manageSubscription: "Gestionar Suscripción",
    manageSubscriptionDesc: "Gestiona tu plan de suscripción de suplementos",
    connectedDevices: "Dispositivos Conectados",
    syncFitnessData: "Sincroniza tus datos de fitness para recomendaciones personalizadas",
    preferences: "Preferencias",
    language: "Idioma",
    darkMode: "Modo Oscuro",
    currentlyEnabled: "Actualmente habilitado",
    notifications: "Notificaciones",
    getHealthReminders: "Recibir recordatorios de salud",
    privacySecurity: "Privacidad y Seguridad",
    manageYourData: "Gestiona tus datos",
    logout: "Cerrar Sesión",
    
    // Profile
    healthJourney: "Tu viaje de salud en resumen",
    bloodTests: "Análisis de Sangre",
    healthScore: "Puntuación de Salud",
    daysActive: "Días Activos",
    achievements: "Logros",
    totalImprovement: "Mejora Total",
    daysTracked: "Días Registrados",
    recentActivity: "Actividad Reciente",
    about: "Acerca de",
    age: "Edad",
    height: "Altura",
    weight: "Peso",
    goal: "Objetivo",
    
    // Dashboard
    healthDashboard: "Panel de Salud",
    trackWellness: "Rastrea tu viaje de bienestar en un solo lugar",
    overview: "Resumen",
    vitalSigns: "Signos Vitales",
    medications: "Medicamentos",
    
    // Common
    backToHome: "Volver al Inicio",
    backToSettings: "Volver a Configuración",
    viewProfile: "Ver Perfil",
    save: "Guardar",
    
    // Notifications
    bloodTestReminder: "Recordatorio de Análisis",
    bloodTestReminderDesc: "Recordatorio cada 3 meses para nuevo análisis",
    supplementReminder: "Recordatorio de Suplementos",
    supplementReminderDesc: "Recordatorio diario de ingesta",
    weeklyReport: "Informe Semanal",
    weeklyReportDesc: "Resumen de tu progreso",
    newRecommendations: "Nuevas Recomendaciones",
    newRecommendationsDesc: "Notificación de nuevos consejos",
    shoppingReminder: "Recordatorio de Compras",
    shoppingReminderDesc: "Lista de compras semanal",
    quietHours: "Horas de Silencio",
    quietHoursDesc: "Sin notificaciones durante este tiempo",
    from: "Desde",
    to: "Hasta",
    manageNotifications: "Gestiona tus notificaciones",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageInternal] = useState(() => {
    return localStorage.getItem('language') || 'de';
  });

  const setLanguage = (lang) => {
    setLanguageInternal(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    // Force re-render of all components using translations
    window.dispatchEvent(new Event('languageChange'));
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};